# Generated by Django 5.2.4 on 2025-08-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_remove_transcriptionentry_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('project_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('call_type', models.CharField(max_length=50)),
                ('ended_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('total_speech_time_seconds', models.IntegerField()),
                ('total_agent_speech_time_seconds', models.IntegerField()),
                ('total_silence_time_seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='webhook.call')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('start_time_seconds', models.FloatField()),
                ('end_time_seconds', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='webhook.call')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='webhook.call')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='webhook.analysis')),
            ],
        ),
    ]
