# Generated by Django 5.2.4 on 2025-08-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_call_analysis_conversation_metadata_participantdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantdata',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='call',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='call',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='ParticipantData',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
