# Generated by Django 5.2.4 on 2025-08-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_remove_participantdata_analysis_remove_metadata_call_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('agent_id', models.CharField(max_length=255)),
                ('event_timestamp', models.IntegerField()),
                ('call_duration_secs', models.IntegerField()),
                ('main_language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_successful', models.CharField(max_length=50)),
                ('transcript_summary', models.TextField()),
                ('call_summary_title', models.CharField(max_length=255)),
                ('evaluation_criteria_results', models.JSONField(default=dict)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='webhook.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('time_in_call_secs', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='webhook.conversation')),
            ],
        ),
    ]
